/*
# Turf Wars Phase 4 — Guest Ally System

## Overview
Adds the Guest Ally mechanic: non-Greek students can be invited to ally with
an org for a specific event, check in with weighted headcount (0.5x normal,
0.75x for national brothers from the same fraternity at another school),
and earn Rush Credentials during rush-designated events.

This is also the data capture layer for cross-campus expansion: every ally
signup records name, email, university, graduation year, and Greek affiliation
status.

## New Tables

### ally_invites
Generated by org members, tied to a specific claim event. Contains a unique
token for the invite link. Expires when the event resolves.
- id, org_id, claim_id (nullable for general invites), token (unique),
  created_by, expires_at, max_uses (nullable), uses_count, created_at

### allies
Lightweight accounts for non-Greek students who ally with an org.
- id, user_id (nullable — links to auth.users if they create an account),
  org_id (the org they're allying with), claim_id (nullable — for event-specific),
  name, email, university, graduation_year,
  greek_status ('member', 'rush', 'unaffiliated'),
  national_brother (boolean — same fraternity, different school),
  headcount_weight (numeric — 0.5 for allies, 0.75 for national brothers),
  rush_credential_earned (boolean — true if they checked in during a rush event),
  created_at, expires_at (tied to event resolution)

### rush_events
Designates a turf claim as a rush event. Rushees who attend and check in
as allies get a Rush Credential in the app.
- id, claim_id, org_id, is_rush_event, created_at

## Modified Tables

### turf_checkins — add ally support
- ally_id (uuid, nullable — references allies if the check-in is from an ally)
- headcount_weight (numeric, default 1.0 — 1.0 for full members, 0.5 for allies,
  0.75 for national brothers)

### turf_claims — add weighted headcount tracking
- attacker_weighted_headcount (numeric, default 0.0 — sum of all check-in weights)
- defender_weighted_headcount (numeric, default 0.0)
  These are used alongside the integer headcount for display. The weighted
  total is what's compared against required_headcount for win determination.

## Security
- ally_invites: public read (token-based), authenticated insert (org members)
- allies: public read (visible to org), authenticated insert (from invite)
- rush_events: public read, org admin insert
- turf_checkins: updated to allow ally-linked check-ins
*/

-- ─── ENUMS ────────────────────────────────────────────────────────────────────

do $$ begin
  create type greek_status as enum ('member', 'rush', 'unaffiliated');
exception when duplicate_object then null;
end $$;

-- ─── ALLY INVITES ─────────────────────────────────────────────────────────────

create table if not exists ally_invites (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references greek_orgs(id) on delete cascade,
  claim_id      uuid references turf_claims(id) on delete cascade,
  token         text not null unique,
  created_by    uuid not null references auth.users(id) on delete cascade,
  expires_at    timestamptz not null,
  max_uses      int,
  uses_count    int not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists ally_invites_token_idx on ally_invites(token);
create index if not exists ally_invites_org_idx on ally_invites(org_id);

-- ─── ALLIES ───────────────────────────────────────────────────────────────────

create table if not exists allies (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid references auth.users(id) on delete set null,
  org_id                uuid not null references greek_orgs(id) on delete cascade,
  claim_id              uuid references turf_claims(id) on delete cascade,
  invite_id             uuid references ally_invites(id) on delete set null,
  name                  text not null,
  email                 text not null,
  university            text,
  graduation_year       int,
  greek_status          greek_status not null default 'unaffiliated',
  national_brother      boolean not null default false,
  headcount_weight      numeric(3,2) not null default 0.50,
  rush_credential_earned boolean not null default false,
  created_at            timestamptz not null default now(),
  expires_at            timestamptz
);

create index if not exists allies_org_idx on allies(org_id);
create index if not exists allies_claim_idx on allies(claim_id);
create index if not exists allies_user_idx on allies(user_id);
create index if not exists allies_email_idx on allies(email);

-- ─── RUSH EVENTS ──────────────────────────────────────────────────────────────

create table if not exists rush_events (
  id            uuid primary key default gen_random_uuid(),
  claim_id      uuid not null references turf_claims(id) on delete cascade,
  org_id        uuid not null references greek_orgs(id) on delete cascade,
  is_rush_event boolean not null default true,
  created_at    timestamptz not null default now(),
  unique (claim_id)
);

create index if not exists rush_events_claim_idx on rush_events(claim_id);
create index if not exists rush_events_org_idx on rush_events(org_id);

-- ─── TURF CHECKINS: Ally support ──────────────────────────────────────────────

alter table turf_checkins
  add column if not exists ally_id          uuid references allies(id) on delete set null,
  add column if not exists headcount_weight numeric(3,2) not null default 1.00;

-- ─── TURF CLAIMS: Weighted headcount ──────────────────────────────────────────

alter table turf_claims
  add column if not exists attacker_weighted_headcount numeric(5,2) not null default 0.00,
  add column if not exists defender_weighted_headcount numeric(5,2) not null default 0.00;

-- ─── RLS ───────────────────────────────────────────────────────────────────────

alter table ally_invites enable row level security;
alter table allies       enable row level security;
alter table rush_events  enable row level security;

-- ally_invites: public read (token-based discovery), org member insert
drop policy if exists "public read ally_invites" on ally_invites;
create policy "public read ally_invites" on ally_invites for select
  to anon, authenticated using (true);

drop policy if exists "org_member insert ally_invites" on ally_invites;
create policy "org_member insert ally_invites" on ally_invites for insert
  to authenticated
  with check (
    exists (select 1 from org_memberships m
      where m.org_id = ally_invites.org_id
        and m.user_id = auth.uid() and m.verified = true)
  );

drop policy if exists "org_member update ally_invites" on ally_invites;
create policy "org_member update ally_invites" on ally_invites for update
  to authenticated
  using (
    exists (select 1 from org_memberships m
      where m.org_id = ally_invites.org_id
        and m.user_id = auth.uid() and m.verified = true)
  )
  with check (
    exists (select 1 from org_memberships m
      where m.org_id = ally_invites.org_id
        and m.user_id = auth.uid() and m.verified = true)
  );

-- allies: public read (org can see their allies), authenticated insert (from invite)
drop policy if exists "public read allies" on allies;
create policy "public read allies" on allies for select
  to anon, authenticated using (true);

drop policy if exists "auth insert allies" on allies;
create policy "auth insert allies" on allies for insert
  to authenticated with check (true);

drop policy if exists "ally update own record" on allies;
create policy "ally update own record" on allies for update
  to authenticated
  using (user_id = auth.uid() or
    exists (select 1 from org_memberships m
      where m.org_id = allies.org_id
        and m.user_id = auth.uid() and m.verified = true))
  with check (user_id = auth.uid() or
    exists (select 1 from org_memberships m
      where m.org_id = allies.org_id
        and m.user_id = auth.uid() and m.verified = true));

-- rush_events: public read, org admin insert
drop policy if exists "public read rush_events" on rush_events;
create policy "public read rush_events" on rush_events for select
  to anon, authenticated using (true);

drop policy if exists "org_admin insert rush_events" on rush_events;
create policy "org_admin insert rush_events" on rush_events for insert
  to authenticated
  with check (
    exists (select 1 from org_memberships m
      where m.org_id = rush_events.org_id
        and m.user_id = auth.uid() and m.role = 'admin' and m.verified = true)
  );

drop policy if exists "org_admin update rush_events" on rush_events;
create policy "org_admin update rush_events" on rush_events for update
  to authenticated
  using (
    exists (select 1 from org_memberships m
      where m.org_id = rush_events.org_id
        and m.user_id = auth.uid() and m.role = 'admin' and m.verified = true)
  )
  with check (
    exists (select 1 from org_memberships m
      where m.org_id = rush_events.org_id
        and m.user_id = auth.uid() and m.role = 'admin' and m.verified = true)
  );